import React from "react";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Gallery from "../components/Gallery";
const Terms = () => {
  const backgroundImageStyle = {
    background: 'url("assets/images/about-bg.png")',
    backgroundSize: '100% 100%',

  };
  document.title = "about";
  document.getElementsByTagName("META")[2].content = "about";
  return (
    <>
      <Header />
      
      <section className="py-5 mt-80">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-md-12">
              <div className="section-heading">
                <h3 className="theme-bg-text ">Terms & Conditions
</h3>
              </div>
            </div>
            <div className="col-md-11 text-center">
            <p style={{ textAlign: 'justify',whiteSpace:"pre-wrap" }}>
            Date Updated: 30th January, 2023

When shopping with us or using one of our services, you trust us with your information. Protecting your privacy and personal data is of the greatest priority for WINTERBERRY DREAMSPACE LLP.
We believe in the importance of transparency, and hence are providing you with the information about the personal data we collect, why it is needed, how it is used and your rights over it.

This privacy policy describes how Winterbear (collectively, “Winterbear”, “we”, “us” or “our”) collect, use, share, and protect our customers’ personal information. It also tells you about the rights and choices you have with respect to your personal information, and how you can reach us to get answers to your questions. Please note, our privacy practices are subject to the applicable laws of the places in which we operate. You will see additional region-specific terms that only apply to customers located in those geographic regions, or as required by applicable laws.

Interpretation and Definitions
The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
• Account means a unique account created for You to access our Service or parts of our Service.
• Company (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to WINTERBERRY DREAMSPACE LLP, 349, 15th cross, 17th main, Sector-4, HSR Layout, Bangalore, Karnataka, India – 560102
• Cookies are small files that are placed on your computer, mobile device or any other device by a website, containing the details of your browsing history on that website among its many uses.
• Device means any device that can access the service such as a computer, a cell phone or a digital tablet.
• Personal Data is any information that relates to an identified or identifiable individual.
• Service refers to the website.
• Service Provider means any natural or legal person who processes the data on behalf of the company. It refers to third-party companies or individuals employed by the company to facilitate the service, to provide the service on behalf of the company, to perform services related to the Service or to assist the company in analyzing how the Service is used.
• Usage Data refers to data collected automatically, either generated by the use of the service or from the service infrastructure itself (for example, the duration of a page visit).
• Website refers to Winterbear, accessible from https://www.winterbear.in/
• “You” means the individual accessing or using the service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
You can click on the following links to go directly to the corresponding sections of this privacy policy.

1. What Our Privacy Policy Covers
2. What Personal Information We Collect
3. How We Collect Your Personal Information
4. Cookies and Similar Tracking Technologies
5. How We Use Your Personal Information
6. How We Share Your Personal Information
7. How We Protect Your Personal Information
8. Your Rights
9. Transmission Of Information to Other Countries
10. Children’s Privacy
11. Communicating With Us
12. Changes To This Policy
13. Notice of Financial Incentive

1. What Our Privacy Policy Covers
This privacy policy covers Winterbear’s customers residing in India, and applies to the personal information Winterbear obtains in various contexts, both online and offline, including when you access or use our websites, native mobile applications or any other applications or services that link to this privacy policy, visit us in our stores, communicate with us, shop with our third-party partners, engage with us on social media, or participate in any of our programs or events.

We may provide different or additional privacy notices in connection with certain activities, programs, and offerings. We may also provide additional “just-in-time” notices that may supplement or clarify our privacy practices or provide you with additional choices regarding your personal information.

Our websites may include links to websites and/or applications operated and maintained by third parties. Please note that we have no control over the privacy practices of websites or applications that we do not own. We encourage you to review the privacy practices of those third parties.

2. What Personal Information We Collect
The types of personal information we obtain about you depends on how you interact with us and our products and services. When we use the term “personal information,” we are referring to information that identifies, relates to, describes, or can be associated with you.

The following are the categories and specific types of personal information that we collect:
• Basic Identifying Information
Including your full name, alias, postal address, email address, phone number, date of birth, account name, signature, username or social media handle, or other similar identifiers.
• Government-Issued Identifiers
Including your driver’s license number, Aadhar number, or other similar government identifier.
• Device Information and Other Unique Identifiers
Including device identifier, internet protocol (IP) address, cookies, beacons, pixel tags, mobile ad identifier, or similar unique identifiers.
• Internet or Other Network Activity
Including browsing or search history, and information regarding your interactions with our websites, mobile applications, emails, or advertisements.
• Geolocation Data
Including information that permits us to determine your location, only if you manually provide location information or enable your mobile device to send us precise location information.
• Payment Information
Including credit or debit card number or UPI or other payment details, inputted by you, onto our site when making payment.
• Orders Information
Including details of the order placed by you to arrange for shipping, communicate with you, and provide you with invoices and/or order confirmation.
• Commercial Information
Including products or services you have purchased, returned, exchanged, or considered, preferences, and rewards activity related to “BEARCLUB” (Winterbear Official Membership).
• Physical Characteristics
Including skin tone and type, hair color and type, eye color, and other beauty profile information you provide.
• Health and Medical Information
Including information you choose to provide regarding skin conditions or medications in connection with a beauty service, in-store digital experience, or product recommendation.
• Demographic Data
Including details like age, gender, race, ethnicity, estimated income, and household information you choose to provide us.
• User Content
Including your communications with us and any other content you provide (such as social media profiles, photographs, images, videos, survey responses, comments, product reviews, testimonials, and other content).
• Audio and Visual Information
Including photographs, images, videos, and recordings of your voice (such as when we record customer service calls for quality assurance).
• Inferences
Inferences drawn from or created based on any of the information identified above.
• Job Applicant Information
Including professional or employment-related information (such as education and employment history) and any other information you provide in connection with applying and interviewing for employment at Winterbear. If we retain you as an employee, this may include, among other things, your Aadhar number or taxpayer ID.

3. How We Collect Your Personal Information
We collect personal information about you from various sources. For example, we collect and obtain information:
• Directly from you
We collect personal information you provide, such as when you make a purchase, pre-order, register for an account or create a profile, sign up for Bearclub, contact us, respond to a survey, RSVP for an event, interact with us in store, participate in sweepstakes, giveaways, events, contests, or other similar campaigns or promotions, apply for a job, or sign up to receive emails, text messages, and/or postal mailings.
• Using cookies and other automatic data collection technologies
When you visit our websites, open or click on emails we send you, or interact with our advertisements, we or third parties we work with automatically collect certain information using technologies such as cookies, web beacons, clear GIF, pixels, internet tags, web server logs, and other data collection tools. For more information, please see “Cookies and Similar Tracking Technologies” section below.
• Through in-store and other offline technologies
In some cases, we record customer service calls for quality assurance. We also use Closed Circuit Television or CCTV in our stores for safety, security, fraud, loss prevention, and operational purposes.
• From our Third-Party Partners
We obtain information from third parties that we have partnered with, and other third parties we choose to collaborate or work with.
• From Social Media Platforms and Networks
If you interact with us on social media or use features, such as plugins, widgets, or other tools made available by social media platforms or networks (including Instagram, Facebook, Twitter, Google, YouTube, Pinterest, Tik Tok) in connection with our websites, we collect information that you share with us, or that the social media platforms share with us. For more information about the privacy practices of those social media platforms, please review the privacy policies and settings of the social media platforms and networks that you use.
• From Other Sources
For example, we may obtain information about you from other sources, such as data analytics providers, marketing or advertising service providers, fraud prevention service providers, vendors that provide services on our behalf, or publicly available sources. We may create information based on our analysis of the information we have collected from you.

4. Cookies and Similar Tracking Technologies
We and our third-party service providers (such as advertising and analytics providers) use cookies (persistent cookies and session cookies), flash cookies, web beacons, clear GIF, pixels, internet tags, and other similar tracking technologies (collectively, ‘tracking technologies”) to gather information when you interact with our websites, and email communications. You can learn more about cookies here: All About Cookies by TermsFeed. Tracking technologies help us maintain the security of our websites and your account, prevent crashes, fix bugs, save your preferences, and assist with basic site functions. These tracking technologies are “required” because we need them for the websites to work properly. We don’t provide the option to opt-out of these tracking technologies, but you can remove these “required” tracking technologies by modifying your browser settings. Please note, some features of our websites may not be available to you as a result.

We permit third parties to use tracking technologies on our websites for analytics to understand how visitors interact with our websites. For example, we use Google Analytics to evaluate website traffic and usage data to help us improve our products and services. For more information about how Google collects and processes data visit https://policies.google.com/technologies/partner-sites. For more information about how to opt out of having your information used by Google Analytics, visit https://tools.google.com/dlpage/gaoptout/, and for Adobe please visit https://www.adobe.com/privacy/opt-out.html.

We also permit third parties to use tracking technologies on our websites for advertising, including to help manage and display advertisements, to tailor advertisements to your interests, or to send abandoned shopping cart reminders. The third parties use their technology to provide advertising about products and services tailored to your interests which may appear either on our websites or on other websites. This is sometimes referred to as third-party behavioral advertising.

5. How We Use Your Personal Information
The Company may use Personal Data for the following purposes:
• To provide and maintain our service, including to monitor the usage of our service.
• To manage your account: to manage your registration as a user of the service. The personal data you provide can give you access to different functionalities of the service that are available to you as a registered user.
• For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services you have purchased or of any other contract with us through the service.
• To contact you: To contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application’s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
• To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opt-out to not to receive such information.
• To manage your requests: To attend and manage your requests to us.
• For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by us about our service users is among the assets transferred.
• For other purposes: we may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our service, products, services, marketing and your experience.

6. How We Share Your Personal Information
In addition to the specific situations discussed elsewhere in this privacy policy, we disclose personal information in the following circumstances:
• Corporate Affiliates
We may share personal information with our corporate affiliates, including our parent company, sister companies and subsidiaries. Such corporate affiliates process personal information on our behalf as our service provider, where necessary to provide a product or service that you have requested, including to administer the Bearclub, or in other circumstances with your consent or as permitted or required by law.
• Service Providers
We share certain personal information with third parties that perform services to support our core business functions and internal operations including: fulfilling orders, delivering packages, complying with your request for the shipment of products to or the provision of services by a third party intermediary, sending postal mail, emails and text messages, analyzing customer data, providing marketing assistance, administering our Ratings & Reviews, supporting beacons, processing credit card and debit card payments, investigating fraudulent activity, conducting customer surveys, and providing customer service.
• Third Party Partners
We may share your personal information with third parties that we have partnered with to jointly create and offer a product, service, or joint promotion. We may also share your personal information with our third party partners in the event we suspect you are violating our terms or engaging in fraudulent behavior as it relates to our business. If you decide to obtain a product or service that is offered by these third party partners, the information you provide will be shared with us and them. Their use of your information is not governed by this privacy policy, but by their own respective privacy policies. Please note, we will not share text messaging opt-in data and consent with any third parties for their marketing purposes.
• Social Media Platforms and Networks
Some of our websites have features such as, plugins, widgets, or and other tools made available by third parties that may result in information being collected or shared between us and the third party. For example, if you use Facebook’s “Like” feature, Facebook may register the fact that you “liked” a product and may post that information on Facebook. Their use of your information is not governed by this privacy policy.
• Public Forums
Some of our websites provide the opportunity to post content in a public forum. For example, Winterbear’s website allows you to participate in the Bearclub, online, provide Ratings & Reviews, and to receive product recommendations. If you decide to submit information in these public forums, that information will be publicly available.
• Legal Process
We may disclose personal information in response to subpoenas, warrants, court orders, government inquiries or investigations, or to comply with relevant laws and regulations. We may also disclose information to establish, exercise, or protect the rights of our company, employees, agents, and affiliates; to defend against a legal claim; to protect the safety and security of our visitors; to detect and protect against fraud; and to take action regarding possible illegal activities or violations of our policies.
• Business Transfers
We may share personal information with another company that buys some, or all, of the assets or stock of Winterberry Dreamspace LLP, and that company may use and disclose personal information for purposes similar to what is described in this policy. Winterbear may also share personal information with prospective purchasers to evaluate the proposed transaction.
• Other Instances
We may ask if you would like us to share your information with other third parties who are not described elsewhere in this privacy policy.

7. How We Protect Your Personal Information
Personal information is maintained on our servers or those of our service providers, and is accessible by authorized employees, representatives, and agents as necessary for the purposes described in this privacy policy.

We realize that individuals trust us to protect their personal information. We maintain reasonable and appropriate physical, electronic and procedural safeguards designed to help protect your personal information. While we attempt to protect your personal information in our possession, no method of transmission over the internet, or security system is perfect, and we cannot promise that information about you will remain secure in all circumstances.
Please notify us as soon as possible if you suspect any unauthorized use of your account or password.

8. Your Rights
Consistent with applicable law, you may exercise the rights described in this section. Please note that some of the rights may vary depending on your country, province, or state of residence.
• Accessing, Updating, Correcting, and Deleting Personal Information
You may have the right to request access to and receive details about the personal information we maintain about you and how we have processed it, update and correct inaccuracies, get a copy of, or delete your personal information. You may also have the right to withdraw your consent to our processing of your personal information. These rights may be limited in some circumstances by applicable law.

• Access and Deletion
You can submit a request to access or delete your personal information, or withdraw consent, or request an explanation of any computer-system decision about you by submitting a request by emailing us at hello@winterbear.in

• Updates and Corrections
You can update information related to your account by:
• Logging into your account on Winterbear.in; or
• Email hello@winterbear.in; or
• By visiting any of the Winterbear stores and speaking with a representative

If you have given Winterbear permission to store your credit card information and you don’t want merchants like Winterbear to receive your updated credit card information through your credit card issuer’s account updater service, please contact your card issuer.

• Identity Verification
For us to process some requests, we will need to verify your identity to confirm that the request came from you. We may contact you by phone or email to verify your request. Depending on your request, we will ask for information such as your name, and an email address that you have used with Winterbear, or a phone number you have used with Winterbear. For certain requests, we may also ask you to provide details about the most recent purchase you made online or in store.

• Managing Communication Preferences
Email
You can stop receiving promotional emails at any time by clicking on the “unsubscribe” link at the bottom of any promotional email that you receive from us;
Postal Mail
You can stop receiving promotional postal mail at any time by emailing us at hello@winterbear.in;
Text Messages
You can opt-out of receiving text messages from us by replying “STOP” to the text message you receive from us. Please note that this will only opt you out of the specific text messaging program associated with that number. For more information, please refer to the Winterbear Text Messaging Terms & Conditions.

9. Transmission of Information to Other Countries
Winterbear is located in India and uses service providers and corporate affiliates that may be located outside of India, including in the United States or other countries.
If you submit personal information to Winterbear, your personal information may be processed in a foreign country where privacy laws may be less stringent than the laws in your country. By submitting your personal information to us you agree to the transfer, storage, and processing of your personal information in a country other than your country of residence including, but not necessarily limited to, the United States.

10. Children’s Privacy
Our website is not intended for or directed to children under the age of 18. We do not knowingly collect personal information directly from children under the age of 18 without parental consent. If we become aware that a child under the age of 18 has provided us with personal information on our website, we will delete the information from our records.

11. Communicating With Us
If you have any questions about Winterbear’s privacy or security practices, you can contact Winterberry Dreamspace LLP by mail, telephone, or email:
WINTERBERRY DREAMSPACE LLP
349, 15th cross, 17th main,
Sector-4, HSR Layout,
Bangalore, Karnataka, India – 560102
hello@winterbear.in
If we need, or are required, to contact you concerning any event that involves your personal information we may do so by email, telephone, or mail.

12. Changes To This Policy
We may revise this privacy policy from time to time and will post the date it was last updated at the top of this privacy policy. We will provide additional notice to you if we make any changes that materially affect your privacy rights.

13. Notice of Financial Incentive
We offer our customers a loyalty program (“BEARCLUB”) that provides certain perks, such as rewards and exclusive offers. We may also provide other programs, such as sweepstakes, contests, or other similar promotional campaigns (collectively, the “Programs”). When you sign up for one of these Programs, we typically ask you to provide your name and contact information (such as email address and/or telephone number). Because our Programs involve the collection of personal information, they might be interpreted as a “financial incentive” program under certain laws. The value of your personal information to us is related to the value of the free or discounted products or services, or other benefits that you obtain or that are provided as part of the applicable Program, less the expense related to offering those products, services, and benefits to Program participants. You may withdraw from participating in a Program at any time by contacting us using the designated method set forth in the applicable Program rules. Visit the terms and conditions page of each Program to view full details, including how to join.
            </p>
            </div>
          </div>
      
        </div>
      </section>
    
      <Gallery />
      <Footer />
    </>
  );
};

export default Terms;
